apiVersion: v1
kind: Secret
metadata:
  name: wsl2-microk8s-lab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/lamadome/wsl2-microk8s-lab
