apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default
  source:
    repoURL: https://github.com/iamgauravpande/wsl2-microk8s-lab.git
    targetRevision: main
    path: observability/applicationsets
  destination:
    server: https://127.0.0.1:16443 ## microk8s control plane 
    namespace: argocd